#############################################################################
# Makefile for building: test
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 9? 11 15:30:34 2015
# Project:  test.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile test.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: test.pro  /usr/local/4.8.7/mkspecs/macx-g++/qmake.conf /usr/local/4.8.7/mkspecs/common/unix.conf \
		/usr/local/4.8.7/mkspecs/common/mac.conf \
		/usr/local/4.8.7/mkspecs/common/gcc-base.conf \
		/usr/local/4.8.7/mkspecs/common/gcc-base-macx.conf \
		/usr/local/4.8.7/mkspecs/common/g++-base.conf \
		/usr/local/4.8.7/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/4.8.7/mkspecs/features/qt_functions.prf \
		/usr/local/4.8.7/mkspecs/features/qt_config.prf \
		/usr/local/4.8.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/4.8.7/mkspecs/features/default_pre.prf \
		/usr/local/4.8.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/4.8.7/mkspecs/features/release.prf \
		/usr/local/4.8.7/mkspecs/features/debug_and_release.prf \
		/usr/local/4.8.7/mkspecs/features/default_post.prf \
		/usr/local/4.8.7/mkspecs/features/mac/default_post.prf \
		/usr/local/4.8.7/mkspecs/features/mac/x86_64.prf \
		/usr/local/4.8.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/4.8.7/mkspecs/features/shared.prf \
		/usr/local/4.8.7/mkspecs/features/warn_on.prf \
		/usr/local/4.8.7/mkspecs/features/qt.prf \
		/usr/local/4.8.7/mkspecs/features/unix/thread.prf \
		/usr/local/4.8.7/mkspecs/features/moc.prf \
		/usr/local/4.8.7/mkspecs/features/mac/rez.prf \
		/usr/local/4.8.7/mkspecs/features/mac/sdk.prf \
		/usr/local/4.8.7/mkspecs/features/resources.prf \
		/usr/local/4.8.7/mkspecs/features/uic.prf \
		/usr/local/4.8.7/mkspecs/features/yacc.prf \
		/usr/local/4.8.7/mkspecs/features/lex.prf \
		/usr/local/4.8.7/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/4.8.7/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.8.7/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile test.pro
/usr/local/4.8.7/mkspecs/common/unix.conf:
/usr/local/4.8.7/mkspecs/common/mac.conf:
/usr/local/4.8.7/mkspecs/common/gcc-base.conf:
/usr/local/4.8.7/mkspecs/common/gcc-base-macx.conf:
/usr/local/4.8.7/mkspecs/common/g++-base.conf:
/usr/local/4.8.7/mkspecs/common/g++-macx.conf:
/usr/local/Cellar/qt/4.8.7/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.7/mkspecs/modules/qt_webkit_version.pri:
/usr/local/4.8.7/mkspecs/features/qt_functions.prf:
/usr/local/4.8.7/mkspecs/features/qt_config.prf:
/usr/local/4.8.7/mkspecs/features/exclusive_builds.prf:
/usr/local/4.8.7/mkspecs/features/default_pre.prf:
/usr/local/4.8.7/mkspecs/features/mac/default_pre.prf:
/usr/local/4.8.7/mkspecs/features/release.prf:
/usr/local/4.8.7/mkspecs/features/debug_and_release.prf:
/usr/local/4.8.7/mkspecs/features/default_post.prf:
/usr/local/4.8.7/mkspecs/features/mac/default_post.prf:
/usr/local/4.8.7/mkspecs/features/mac/x86_64.prf:
/usr/local/4.8.7/mkspecs/features/mac/objective_c.prf:
/usr/local/4.8.7/mkspecs/features/shared.prf:
/usr/local/4.8.7/mkspecs/features/warn_on.prf:
/usr/local/4.8.7/mkspecs/features/qt.prf:
/usr/local/4.8.7/mkspecs/features/unix/thread.prf:
/usr/local/4.8.7/mkspecs/features/moc.prf:
/usr/local/4.8.7/mkspecs/features/mac/rez.prf:
/usr/local/4.8.7/mkspecs/features/mac/sdk.prf:
/usr/local/4.8.7/mkspecs/features/resources.prf:
/usr/local/4.8.7/mkspecs/features/uic.prf:
/usr/local/4.8.7/mkspecs/features/yacc.prf:
/usr/local/4.8.7/mkspecs/features/lex.prf:
/usr/local/4.8.7/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/4.8.7/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.8.7/lib/QtCore.framework/QtCore.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile test.pro

qmake_all: FORCE

make_default: release-make_default debug-make_default FORCE
make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
